version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: smartreplenishdb
      POSTGRES_USER: smartreplenishdb_owner
      POSTGRES_PASSWORD: npg_r5jewgR8XGko
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ../backend
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://smartreplenishdb_owner:npg_r5jewgR8XGko@db:5432/smartreplenishdb
    ports:
      - "5000:5000"
    depends_on:
      - db
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  pgdata: 